const facil= ["La casa grande y blanca está ubicada en el centro del pueblo. El jardín delantero está lleno de flores coloridas y el aroma del jazmín llena el aire. Los niños juegan felices en la calle mientras el sol brilla en lo alto. Dentro de la casa, la familia se reúne alrededor de la mesa para disfrutar de una comida caliente y sabrosa.",
"El bosque tranquilo y frondoso es el hogar de muchos animales. Los árboles altos y robustos proporcionan refugio a las aves y a los pequeños mamíferos. El arroyo serpentea suavemente a través del bosque, ofreciendo agua fresca y limpia a todas las criaturas que la necesitan. El sol filtra entre las hojas verdes, creando un juego de luces y sombras en el suelo del bosque.",
"En la granja, los animales están ocupados con sus quehaceres diarios. Las vacas pacen en el campo, mientras que los cerdos revuelcan en el barro. El granjero trabaja en los campos, sembrando y cosechando los cultivos. Los niños corren y juegan alrededor del granero, riendo y disfrutando del aire fresco del campo. Al final del día, todos se reúnen para una cena abundante y reconfortante.",
"La imponente edificación de estilo neoclásico se alza majestuosa en el corazón de la ciudad. Sus columnas corintias sostienen un frontón decorado con relieves que narran la historia de la antigua civilización. Los transeúntes se detienen a contemplar su esplendor mientras el sol se refleja en las ventanas de cristal tintado. En su interior, los visitantes pueden admirar obras de arte de valor incalculable y recorrer sus intrincados pasillos.",
"El río caudaloso serpentea entre las montañas, formando meandros que dan vida a la exuberante vegetación que lo rodea. Sus aguas cristalinas reflejan el intenso azul del cielo y la belleza de los bosques que lo bordean. A lo largo de sus orillas, se pueden encontrar pequeños pueblos pesqueros donde los habitantes viven en armonía con la naturaleza, aprovechando los recursos que el río les ofrece.",
"La sinfonía resonante de la orquesta llena el majestuoso teatro con una atmósfera de emoción y belleza. Los músicos, dirigidos por el talentoso director, ejecutan cada nota con precisión y pasión, transportando al público a un mundo de sensaciones y emociones. Las luces tenues iluminan el escenario, destacando la elegancia de los instrumentos y la destreza de los intérpretes.",
"La arquitectura neogótica de la catedral gótica se erige imponente en el centro histórico de la metrópolis. Sus contrafuertes y arbotantes sostienen una nave central de proporciones monumentales, mientras que las tracerías de las vidrieras filtran la luz solar en un juego de colores etéreos. Los feligreses se congregan en su interior para contemplar el misticismo que emana de cada rincón, sumergiéndose en la contemplación espiritual.",
"El fenómeno meteorológico de la supercélula se forma en la atmósfera como resultado de la inestabilidad atmosférica y el alto contenido de humedad. Sus características distintivas incluyen una mesociclón bien definida y una pared de nubes en forma de hoz. Los meteorólogos vigilan de cerca estos eventos debido a su potencial para generar tornados destructivos y granizo de gran tamaño.",
"La partícula subatómica conocida como quark es un constituyente fundamental de la materia, y su comportamiento dentro del modelo estándar de la física de partículas ha sido objeto de intensa investigación. Los quarks exhiben propiedades de carga fraccional y están confinados dentro de los hadrones debido a la fuerte interacción nuclear. Su estudio ha llevado al desarrollo de teorías fundamentales sobre la estructura del universo a escalas microscópicas."
]